# Project Assignment #2
# 
# Assignment: Caching the Inverse of a Matrix
# >>TEST & RESULTS AT END OF CODE<<

# Write the following functions:
# 1) makeCacheMatrix(): This function creates a special "matrix" object that can
# cache its inverse. 
# 2) cacheSolve(): This function computes the inverse of the
# special "matrix" returned by makeCacheMatrix above. If the inverse has already
# been calculated (and the matrix has not changed), then the cachesolve should
# retrieve the inverse from the cache.

# Computing the inverse of a square matrix can be done with the solve() function
# in R. For this assignment, assume that the matrix supplied is always invertible.

#makecacheMatrix() Creates a list of 4 functions with calculated values of
# input matrix 'x' & the inverse of 'x'
# input matrix can generated using general matrix form 
# matrix(data = NA, nrow = 1, ncol = 1, byrow = FALSE, dimnames = NULL)

makecacheMatrix <- function(x = matrix()) {
  s <- NULL
  set <- function(y) {
    x <<- y
    s <<- NULL
  }
  get <- function() x
  setInverse <- function(solve) s <<- solve
  getInverse <- function() s
  list(set = set, get = get,
       setInverse = setInverse,
       getInverse = getInverse)
}


## cacheSolve()  Return a matrix that is the inverse of 'x'

cacheSolve <- function(x, ...) {
  s <- x$getInverse()
  if(!is.null(s)) {
    message("getting cached data")
    return(s)
  }
  data <- x$get()
  s <- solve(data, ...)
  x$setInverse(s)
  s
}

# TEST DATA & RESULTS:
# --------------------
# INPUT MATRIX;:
# > ma<-matrix(1:4,ncol=2,nrow=2,byrow=TRUE)
###
# > ma
#      [,1] [,2]
# [1,]    1    2
# [2,]    3    4
###
# > mat<-makecacheMatrix(ma)
# List of functions generated by makecacheMatrix()
# > mat
# $set
# function (y) 
# {
#   x <<- y
#   s <<- NULL
# }
# <environment: 0x4f883a0>
#   
#   $get
# function () 
#   x
# <environment: 0x4f883a0>
#   
#   $setInverse
# function (solve) 
#   s <<- solve
# <environment: 0x4f883a0>
#   
#   $getInverse
# function () 
#   s
# <environment: 0x4f883a0>
# Original matrix stored inside makecacheMatrix()
# > mat$get()
#      [,1] [,2]
# [1,]    1    2
# [2,]    3    4


# INVERSE MATRIX generated using solve()
# > csi<-cacheSolve(mat) 
# > csi
#      [,1] [,2]
# [1,] -2.0  1.0
# [2,]  1.5 -0.5
# INPUT multiplied by INVERSE should give Identity Matrix
# > ma%*%csi
#      [,1]         [,2]
# [1,]    1 1.110223e-16
# [2,]    0 1.000000e+00
# ROUNDED IDENTITY MATRIX. Hence code is working properly!!!
# > round(ma%*%csi)
#      [,1] [,2]
# [1,]    1    0
# [2,]    0    1
# Repeating same calculation again gives the CACHED value.
# > csi<-cacheSolve(mat)
# getting cached data
# > csi
#      [,1] [,2]
# [1,] -2.0  1.0
# [2,]  1.5 -0.5



# 1) Fork the GitHub repository containing the stub R files at
# https://github.com/rdpeng/ProgrammingAssignment2 to create a copy under your
# own account. 
# Ans: Click on the 'Fork' button. 
# Gets forked at https://github.com/fortunewalla/ProgrammingAssignment2
#
# 2) Clone your forked GitHub repository to your computer so that you
# can edit the files locally on your own machine. Edit the R file contained in
# the git repository and place your solution in that file (please do not rename
# the file). 
# Ans: $git clone https://github.com/fortunewalla/ProgrammingAssignment2.git
#      $git add cacheMatrix.R
# 3) Commit your completed R file into YOUR git repository and push your
# git branch to the GitHub repository under your account. 
# Ans: $git commit -m "PA 2 - creating a cache matrix" cacheMatrix.R
#      $git push
#
# Submit to Coursera the URL to your GitHub repository that contains the 
# completed R code for the assignment.
